version: '3.8'

services:
  weather_fetcher:
    image: python:3.8-slim
    container_name: weather_fetcher
    volumes:
      - .:/app
    working_dir: /app
    command: python fetch_weather.py
    environment:
      - API_URL=http://mockweatherapi.com/weather
      - API_KEY=your_api_key_here
